import { PhoneticMap } from './types';

// Phonetic mappings for ALL words in PGM V. 96-172 (The Bornless Ritual).
// These are used to drive ElevenLabs TTS with accurate ancient Greek pronunciation.
// Keys must exactly match tokens as they appear in the ritual body text.
export const FALLBACK_PHONETICS: PhoneticMap = {
  // ── Common Greek words (prose) ──────────────────────────────────────────
  'Σὲ':               'seh',
  'σὲ':               'seh',
  'καλῶ':             'kah-loh',
  'τὸν':              'ton',
  'τὸ':               'to',
  'τῷ':               'toh',
  'τὴν':              'tayn',
  'τῆς':              'tays',
  'τῶν':              'tone',
  'τοῦ':              'too',
  'τοῖς':             'tois',
  'τοὺς':             'toos',
  'τὰ':               'tah',
  'Ἀκέφαλον':         'ah-keh-fah-lon',
  'Ἀκέφαλε':          'ah-keh-fah-leh',
  'Ἀκέφαλος':         'ah-keh-fah-los',
  'κτίσαντα':         'ktee-sahn-tah',
  'γῆν':              'gayn',
  'γῆ':               'gay',
  'καὶ':              'keh',
  'οὐρανόν':          'oo-rah-non',
  'νύκτα':            'neek-tah',
  'ἡμέραν':           'hay-meh-rahn',
  'φῶς':              'fohs',
  'σκότος':           'skoh-tos',
  'Σὺ':               'soo',
  'σὺ':               'soo',
  'σου':              'soo',
  'σοῦ':              'soo',
  'εἶ':               'ay',
  'Ὀσοροννωφρις':     'oh-soh-ron-noh-frees',
  'ὃν':               'hon',
  'οὗ':               'hoo',
  'οὐδεὶς':           'oo-dees',
  'εἶδε':             'ay-deh',
  'πώποτε':           'poh-poh-teh',
  'διέκρινας':        'dee-eh-kree-nahs',
  'δίκαιον':          'dee-keh-on',
  'ἄδικον':           'ah-dee-kon',
  'ἐποίησας':         'eh-poy-ay-sahs',
  'θῆλυ':             'thay-loo',
  'ἄρρεν':            'ah-ren',
  'ἔδειξας':          'eh-dex-ahs',
  'σπορὰν':           'spoh-rahn',
  'καρπούς':          'kar-poos',
  'ἀνθρώπους':        'an-throh-poos',
  'ἀλληλοφιλεῖν':     'ah-lay-loh-fee-len',
  'ἀλληλομισεῖν':     'ah-lay-loh-mee-sen',
  
  // ── Moses Invocation words ──────────────────────────────────────────────
  'Ἐγώ':              'eh-goh',
  'εἰμι':             'ay-mee',
  'Μοϋσῆς':           'moh-oo-says',
  'ὁ':                'ho',
  'ἡ':                'hay',
  'προφήτης':         'proh-fay-tays',
  'προφήταις':        'proh-fay-tais',
  'ᾧ':                'hoh',
  'παρέδωκας':        'pah-reh-doh-kahs',
  'μυστήριά':         'mee-stay-ree-ah',
  'συντελούμενα':     'seen-teh-loo-meh-nah',
  'Ἰστραήλ':          'ee-strah-ayl',
  'ὑγρὸν':            'ee-gron',
  'ξηρὸν':            'ksay-ron',
  'πᾶσαν':            'pah-sahn',
  'τροφήν':           'troh-fayn',
  'Ἐπάκουσόν':        'eh-pah-koo-son',
  'μου':              'moo',
  'μοι':              'moy',
  'ἄγγελος':          'ahn-geh-los',
  'Φαπρω':            'fah-proh',
  'Τοῦτό':            'too-toh',
  'ἐστιν':            'eh-steen',
  'ὄνομα':            'oh-noh-mah',
  'ὄνομά':            'oh-noh-mah',
  'ἀληθινὸν':         'ah-lay-thee-non',
  'παραδιδόμενον':    'pah-rah-dee-doh-meh-non',
  'Εἰσάκουσόν':       'ay-sah-koo-son',
  'ἀποστρεψον':       'ah-poh-strep-son',
  'δαιμόνιον':        'deh-moh-nee-on',
  'δαίμονος':         'deh-moh-nos',
  'Δαίμων':           'deh-mohn',
  'τοῦτο':            'too-toh',
  
  // ── Headless Invocation words ───────────────────────────────────────────
  'Ἐπικαλοῦμαί':      'eh-pee-kah-loo-meh',
  'σε':               'seh',
  'ἐν':               'en',
  'κενῷ':             'keh-noh',
  'πνεύματι':         'pnev-mah-tee',
  'δεινὸν':           'day-non',
  'δεῖνα':            'day-nah',
  'ἀόρατον':          'ah-oh-rah-ton',
  'θεὸν':             'theh-on',
  'θεοῦ':             'theh-oo',
  'θεῶν':             'theh-ohn',
  'Ἅγιε':             'hah-gee-eh',
  'Ἀπάλλαξον':        'ah-pahl-lah-kson',
  'ἀπὸ':              'ah-poh',
  'συνέχοντος':       'see-neh-khon-tos',
  'αὐτὸν':            'ahf-ton',
  'Ἰσχυρὲ':           'ee-skhee-reh',
  'Ἰσχυρὸς':          'ee-skhee-ros',
  
  // ── Lord of the Gods words ──────────────────────────────────────────────
  'Οὗτος':            'hoo-tos',
  'κύριος':           'kee-ree-os',
  'Κύριε':            'kee-ree-eh',
  'οἰκουμένης':       'oy-koo-meh-nays',
  'ὂν':               'on',
  'οἱ':               'hoy',
  'ἄνεμοι':           'ah-neh-moy',
  'φοβοῦνται':        'foh-boon-teh',
  'ποιήσας':          'poy-ay-sahs',
  'φωνῆς':            'foh-nays',
  'προστάγματι':      'proh-stahg-mah-tee',
  'ἑαυτοῦ':           'heh-ahf-too',
  'πάντα':            'pahn-tah',
  'Βασιλεῦ':          'bah-see-lev',
  'Δυνάστα':          'dee-nah-stah',
  'Βοηθέ':            'boh-ay-theh',
  'Σῶσον':            'soh-son',
  'ψυχὴν':            'psee-khayn',
  'ΕΗδη':             'ay-ay-day',
  'εδη':              'eh-day',
  'εὐαγγελος':        'ev-ahn-geh-los',
  
  // ── Self-Identification words ───────────────────────────────────────────
  'ποσὶν':            'poh-seen',
  'ἔχων':             'eh-khohn',
  'ὅρασιν':           'hoh-rah-seen',
  'πῦρ':              'peer',
  'ἀθάνατον':         'ah-thah-nah-ton',
  'Ἀλήθεια':          'ah-lay-thay-ah',
  'μισῶν':            'mee-sohn',
  'ἀδικήματα':        'ah-dee-kay-mah-tah',
  'γίνεσθαι':         'gee-neh-stheh',
  'κόσμῳ':            'koz-moh',
  'ἀστράπτων':        'ah-strahp-tohn',
  'βροντῶν':          'bron-tohn',
  'ἱδρὼς':            'hee-drohs',
  'ὄμβρος':           'om-bros',
  'ἐπιπίπτων':        'eh-pee-peep-tohn',
  'ἐπὶ':              'eh-pee',
  'ἵνα':              'hee-nah',
  'ὀχεύῃ':            'oh-khev-ay',
  'στόμα':            'stoh-mah',
  'καίεται':          'keh-eh-teh',
  'δι\'':             'dee',
  'ὅλου':             'hoh-loo',
  'γεννῶν':           'geh-nohn',
  'ἀπογεννῶν':        'ah-poh-geh-nohn',
  'Χάρις':            'khah-rees',
  'Αἰῶνος':           'eh-oh-nos',
  'καρδία':           'kar-dee-ah',
  'περιεζωσμένη':     'peh-ree-eh-zoh-smeh-nay',
  'ὄφιν':             'oh-feen',
  'Ἔξελθε':           'ex-el-theh',
  'ἀκολούθησον':      'ah-koh-loo-thay-son',

  // ── Core voces magicae (original spec) ──────────────────────────────────
  'IAŌ':              'ee-ah-oh',
  'ΙΑΩ':              'ee-ah-oh',
  'SABAŌTH':          'sah-bah-oat',
  'ΣΑΒΑΩΘ':           'sah-bah-oat',
  'ADŌNAI':           'ah-doh-nye',
  'ΑΔΩΝΑΙ':           'ah-doh-nye',
  'ABRASAX':          'ah-brah-sax',
  'ΑΒΡΑΣΑΞ':          'ah-brah-sax',
  'AŌTH':             'ah-ote',
  'ΑΩΘ':              'ah-ote',
  'ABRAŌTH':          'ah-brah-ote',
  'ΑΒΡΑΩΘ':           'ah-brah-ote',
  'BASUM':            'bah-soom',
  'ΒΑΣΥΜ':            'bah-soom',
  'ISAK':             'ee-sahk',
  'ΙΣΑΚ':             'ee-sahk',

  // ── Opening voces magicae ────────────────────────────────────────────────
  'ΙΑΒΑΣ':            'ee-ah-bahs',
  'ΙΑΠΩΣ':            'ee-ah-pohs',

  // ── Moses invocation barbarous names ────────────────────────────────────
  'ΑΡΒΑΘΙΑΩ':         'ar-bah-thee-ah-oh',
  'ΡΕΙΒΕΤ':           'ray-bet',
  'ΑΘΕΛΕΒΕΡΣΗΘ':      'ah-theh-leh-ber-seth',
  'ΑΡΑ':              'ah-rah',
  'ΒΛΑΘΑ':            'blah-thah',
  'ΑΛΒΕΥ':            'al-bev',
  'ΕΒΕΝΦΧΙ':          'eh-ben-fkhee',
  'ΧΙΤΑΣΓΟΗ':         'khee-tahs-goh-ay',
  'ΙΒ':               'eeb',
  'ΑΒΑΩΘ':            'ah-bah-ote',

  // ── Headless invocation barbarous names ─────────────────────────────────
  'ΑΡΟΓΟΓΟΡΟΒΡΑΩ':    'ah-roh-goh-goh-roh-brah-oh',
  'ΣΟΧΟΥ':            'soh-khoo',
  'ΜΟΔΟΡΙΩ':          'moh-doh-ree-oh',
  'ΦΑΛΑΡΧΑΩ':         'fah-lar-khah-oh',
  'ΟΟΟ':              'oh-oh-oh',
  'ΡΟΥΒΡΙΑΩ':         'roo-bree-ah-oh',
  'ΜΑΡΙ':             'mah-ree',
  'ΩΔΑΜ':             'oh-dahm',
  'ΒΑΑΒΝΑΒΑΩΘ':       'bah-ab-nah-bah-ote',
  'ΑΣΣ':              'ahss',
  'ΑΦΝΙΑΩ':           'af-nee-ah-oh',
  'ΙΘΩΛΗΘ':           'ee-thoh-layth',
  'ΑΗΩΩΥ':            'ah-ay-oh-oh-oo',
  'ΜΑΒΑΡΡΑΙΩ':        'mah-bar-rah-ee-oh',
  'ΙΟΗΛ':             'ee-oh-ayl',
  'ΚΟΘΑ':             'koh-thah',
  'ΑΘΟΡΗΒΑΛΩ':        'ah-thoh-ray-bah-loh',

  // ── Lord of the Gods voces magicae ───────────────────────────────────────
  'ΙΕΟΥ':             'ee-eh-oo',
  'ΠΥΡ':              'peer',
  'ΙΟΥ':              'ee-oo',
  'ΙΑΩΤ':             'ee-ah-oat',
  'ΙΑΗΩ':             'ee-ah-ay-oh',
  'ΙΟΟΥ':             'ee-oh-oo',
  'ΣΑΒΡΙΑΜ':          'sah-bree-ahm',
  'ΟΟ':               'oh-oh',
  'ΥΥ':               'oo-oo',
  'ΕΥ':               'ev',
  'ΑΝΛΑΛΑ':           'an-lah-lah',
  'ΛΑΙ':              'lah-ee',
  'ΓΑΙΑ':             'gah-ee-ah',
  'ΑΠΑ':              'ah-pah',
  'ΔΙΑΧΑΝΝΑ':         'dee-ah-khan-nah',
  'ΧΟΡΥΝ':            'khoh-reen',
};
